# Numpy


NumPy is a powerful Python library used for numerical computing, especially for operations on large, multi-dimensional arrays and matrices. It provides a wide range of mathematical functions to perform complex calculations, including linear algebra, statistical, and Fourier analysis operations, with optimized speed and efficiency

In [2]:
!pip install numpy

In [3]:
import numpy as np

CRUD - Create, Read, Update, Delete. 

### Create

In [4]:
a = np.random.rand()

a

0.43220138366026606

In [5]:
b = np.zeros(5, int)

b

array([0, 0, 0, 0, 0])

In [6]:
c = np.ones((2,2,2))

c

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [7]:
d = np.empty((10,4,2))

d

array([[[7.46039125e-322, 0.00000000e+000],
        [0.00000000e+000, 2.12199579e-314],
        [0.00000000e+000, 4.99006302e-322],
        [0.00000000e+000, 0.00000000e+000]],

       [[6.36598737e-314, 2.12199579e-314],
        [3.45845952e-322, 0.00000000e+000],
        [0.00000000e+000, 6.36598737e-314],
        [2.12199579e-314, 4.94065646e-322]],

       [[0.00000000e+000, 0.00000000e+000],
        [6.36598737e-314, 2.12199579e-314],
        [4.10074486e-322, 0.00000000e+000],
        [0.00000000e+000, 6.36598737e-314]],

       [[2.12199579e-314, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+0

In [8]:
e = np.arange(5)

e

array([0, 1, 2, 3, 4])

In [9]:
x = np.random.rand (3,3,5)

x

array([[[0.96569938, 0.04892599, 0.09476336, 0.65939737, 0.11224839],
        [0.12254289, 0.99683439, 0.87048874, 0.75011009, 0.85576456],
        [0.02538878, 0.5498957 , 0.35638938, 0.51882917, 0.52321017]],

       [[0.86523497, 0.14491372, 0.52273944, 0.9294497 , 0.61506663],
        [0.2008709 , 0.89814678, 0.06959926, 0.4559489 , 0.71578391],
        [0.43960978, 0.11793794, 0.12036833, 0.52686436, 0.70369556]],

       [[0.54074655, 0.09917762, 0.41904283, 0.5474296 , 0.93188769],
        [0.39182778, 0.45045847, 0.85821924, 0.12053626, 0.32593499],
        [0.48925806, 0.19268181, 0.16662824, 0.26735781, 0.18451476]]])

In [10]:
y = np.arange(1, 46).reshape(3, 3, 5)

y

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45]]])

In [11]:
#  an array from an array

z = e[1:4]

z

array([1, 2, 3])

### Read

##### Attributes

In [12]:
x.shape 

(3, 3, 5)

In [13]:
y.size

45

In [14]:
x.dtype

dtype('float64')

In [15]:
print(y.dtype)

int32


##### Indexing & Slicing

In [16]:
y[0]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [20]:
y[0: 2]

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [21]:
y[0][0][0]

1

### Update

##### Arithmetic


In [22]:
add = np.add(x, y)
sub = np.subtract(x, y)
div = np.divide(x, y)
mult = np.multiply(x, y)

In [26]:
mult

array([[[ 0.96569938,  0.09785197,  0.28429009,  2.63758947,
          0.56124196],
        [ 0.73525734,  6.97784074,  6.96390989,  6.75099079,
          8.55764559],
        [ 0.27927661,  6.59874838,  4.633062  ,  7.26360835,
          7.8481526 ]],

       [[13.84375954,  2.46353322,  9.40930996, 17.65954422,
         12.30133262],
        [ 4.21828896, 19.75922905,  1.60078306, 10.94277357,
         17.89459775],
        [11.42985421,  3.18432449,  3.37031325, 15.27906639,
         21.11086688]],

       [[16.76314295,  3.17368381, 13.82841327, 18.61260627,
         32.61606926],
        [14.10580009, 16.66696332, 32.61233119,  4.70091406,
         13.03739945],
        [20.05958051,  8.0926359 ,  7.16501413, 11.76374352,
          8.30316425]]])

##### Conversion


In [27]:
x1 = x[np.newaxis,:]

x1

array([[[[0.96569938, 0.04892599, 0.09476336, 0.65939737, 0.11224839],
         [0.12254289, 0.99683439, 0.87048874, 0.75011009, 0.85576456],
         [0.02538878, 0.5498957 , 0.35638938, 0.51882917, 0.52321017]],

        [[0.86523497, 0.14491372, 0.52273944, 0.9294497 , 0.61506663],
         [0.2008709 , 0.89814678, 0.06959926, 0.4559489 , 0.71578391],
         [0.43960978, 0.11793794, 0.12036833, 0.52686436, 0.70369556]],

        [[0.54074655, 0.09917762, 0.41904283, 0.5474296 , 0.93188769],
         [0.39182778, 0.45045847, 0.85821924, 0.12053626, 0.32593499],
         [0.48925806, 0.19268181, 0.16662824, 0.26735781, 0.18451476]]]])

##### Operators in array


In [29]:
y + e

array([[[ 1,  3,  5,  7,  9],
        [ 6,  8, 10, 12, 14],
        [11, 13, 15, 17, 19]],

       [[16, 18, 20, 22, 24],
        [21, 23, 25, 27, 29],
        [26, 28, 30, 32, 34]],

       [[31, 33, 35, 37, 39],
        [36, 38, 40, 42, 44],
        [41, 43, 45, 47, 49]]])

In [30]:
y * a

array([[[ 0.43220138,  0.86440277,  1.29660415,  1.72880553,
          2.16100692],
        [ 2.5932083 ,  3.02540969,  3.45761107,  3.88981245,
          4.32201384],
        [ 4.75421522,  5.1864166 ,  5.61861799,  6.05081937,
          6.48302075]],

       [[ 6.91522214,  7.34742352,  7.77962491,  8.21182629,
          8.64402767],
        [ 9.07622906,  9.50843044,  9.94063182, 10.37283321,
         10.80503459],
        [11.23723598, 11.66943736, 12.10163874, 12.53384013,
         12.96604151]],

       [[13.39824289, 13.83044428, 14.26264566, 14.69484704,
         15.12704843],
        [15.55924981, 15.9914512 , 16.42365258, 16.85585396,
         17.28805535],
        [17.72025673, 18.15245811, 18.5846595 , 19.01686088,
         19.44906226]]])

In [31]:
y/x


array([[[  1.03551894,  40.87807229,  31.6578037 ,   6.06614494,
          44.54406762],
        [ 48.96244914,   7.02222963,   9.19023954,  11.99823886,
          11.68545705],
        [433.26219916,  21.8223202 ,  36.47695631,  26.98383374,
          28.66916733]],

       [[ 18.49208657, 117.31118467,  34.43398096,  20.44220368,
          32.51680224],
        [104.54475825,  24.49488281, 330.46326676,  52.63747772,
          34.92674206],
        [ 59.14336155, 228.93395497, 232.61932732,  55.04263013,
          42.63207214]],

       [[ 57.32815159, 322.6534403 ,  78.75090066,  62.10844324,
          37.55817386],
        [ 91.87709962,  82.13853799,  44.27773015, 323.55409595,
         122.72386114],
        [ 83.80035661, 217.97595026, 258.05950513, 164.57346228,
         243.88292685]]])

In [32]:
y.sum()

1035

In [33]:
y.min()

1

In [34]:
y.max()

45

##### Unique Values


In [35]:
np.unique (x)

array([0.02538878, 0.04892599, 0.06959926, 0.09476336, 0.09917762,
       0.11224839, 0.11793794, 0.12036833, 0.12053626, 0.12254289,
       0.14491372, 0.16662824, 0.18451476, 0.19268181, 0.2008709 ,
       0.26735781, 0.32593499, 0.35638938, 0.39182778, 0.41904283,
       0.43960978, 0.45045847, 0.4559489 , 0.48925806, 0.51882917,
       0.52273944, 0.52321017, 0.52686436, 0.54074655, 0.5474296 ,
       0.5498957 , 0.61506663, 0.65939737, 0.70369556, 0.71578391,
       0.75011009, 0.85576456, 0.85821924, 0.86523497, 0.87048874,
       0.89814678, 0.9294497 , 0.93188769, 0.96569938, 0.99683439])

In [36]:
np.unique(y)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [37]:
np.unique(b)

array([0])

### Delete

In [38]:
np.delete(x,0,axis=1)

array([[[0.12254289, 0.99683439, 0.87048874, 0.75011009, 0.85576456],
        [0.02538878, 0.5498957 , 0.35638938, 0.51882917, 0.52321017]],

       [[0.2008709 , 0.89814678, 0.06959926, 0.4559489 , 0.71578391],
        [0.43960978, 0.11793794, 0.12036833, 0.52686436, 0.70369556]],

       [[0.39182778, 0.45045847, 0.85821924, 0.12053626, 0.32593499],
        [0.48925806, 0.19268181, 0.16662824, 0.26735781, 0.18451476]]])

In [40]:
x

array([[[0.96569938, 0.04892599, 0.09476336, 0.65939737, 0.11224839],
        [0.12254289, 0.99683439, 0.87048874, 0.75011009, 0.85576456],
        [0.02538878, 0.5498957 , 0.35638938, 0.51882917, 0.52321017]],

       [[0.86523497, 0.14491372, 0.52273944, 0.9294497 , 0.61506663],
        [0.2008709 , 0.89814678, 0.06959926, 0.4559489 , 0.71578391],
        [0.43960978, 0.11793794, 0.12036833, 0.52686436, 0.70369556]],

       [[0.54074655, 0.09917762, 0.41904283, 0.5474296 , 0.93188769],
        [0.39182778, 0.45045847, 0.85821924, 0.12053626, 0.32593499],
        [0.48925806, 0.19268181, 0.16662824, 0.26735781, 0.18451476]]])

In [42]:
np.delete(y,0,axis=2)

array([[[ 2,  3,  4,  5],
        [ 7,  8,  9, 10],
        [12, 13, 14, 15]],

       [[17, 18, 19, 20],
        [22, 23, 24, 25],
        [27, 28, 29, 30]],

       [[32, 33, 34, 35],
        [37, 38, 39, 40],
        [42, 43, 44, 45]]])

In [43]:
y

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45]]])

--- END ---